# Generated by Django 6.0 on 2025-12-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
